### ISSUE TITLE
add download links directly on get started page under step 1 (to be added with hidden thank you page functionality)

### ISSUE THREAD

**Issue by akernest** [cassiopaia/labs.bitshares.org#16]
to clarify, this url (https://bitshares.org/resources/thankyou) still needs to load to fire tracking codes, but should be done in a hidden iframe window that the user cannot see. this also means that the user won’t be redirect anywhere and can continue on the current page.

**Comment by cassiopaia** [comment]
really? So user has to go back to get started page after download software! I'm advise to avoid clicks then needed... just said!

**Comment by cassiopaia** [comment]
ok

**Comment by akernest** [comment]
if the user chooses to go to the get started page instead of download page, dan doesn't want the user to ever leave the get started page in order to download client. so we need to add download icons to get started page and make sure thank you page loads in iframe behind the scenes when user clicks on any of the download links. again, if you don't know how to accomplish this, please contact dan for further instruction.

**Comment by cassiopaia** [comment]
ok, so we've to update then on 2 locations everytime ... jsut said…have to check how to solve this

**Comment by cassiopaia** [comment]
https://github.com/cassiopaia/labs.bitshares.org/commit/318ce93b2b8b113764a03d52d01333f36f5cd810

**Comment by cassiopaia** [comment]
have to add hidden frame!

**Comment by cassiopaia** [comment]
mh have to get more infos about hidden frame for tracking!
http://www.blastam.com/blog/index.php/2013/03/how-to-track-downloads-in-google-analytics-v2

```
<script type="text/javascript">
if (typeof jQuery != 'undefined') {
	jQuery(document).ready(function($) {
		var filetypes = /\.(zip|exe|pdf|doc*|xls*|ppt*|mp3)$/i;
		var baseHref = '';
		if (jQuery('base').attr('href') != undefined)
			baseHref = jQuery('base').attr('href');
		jQuery('a').each(function() {
			var href = jQuery(this).attr('href');
			if (href && (href.match(/^https?\:/i)) && (!href.match(document.domain))) {
				jQuery(this).click(function() {
					var extLink = href.replace(/^https?\:\/\//i, '');
					_gaq.push(['_trackEvent', 'External', 'Click', extLink]);
					if (jQuery(this).attr('target') != undefined && jQuery(this).attr('target').toLowerCase() != '_blank') {
						setTimeout(function() { location.href = href; }, 200);
						return false;
					}
				});
			}
			else if (href && href.match(/^mailto\:/i)) {
				jQuery(this).click(function() {
					var mailLink = href.replace(/^mailto\:/i, '');
					_gaq.push(['_trackEvent', 'Email', 'Click', mailLink]);
				});
			}
			else if (href && href.match(filetypes)) {
				jQuery(this).click(function() {
					var extension = (/[.]/.exec(href)) ? /[^.]+$/.exec(href) : undefined;
					var filePath = href;
					_gaq.push(['_trackEvent', 'Download', 'Click-' + extension, filePath]);
					if (jQuery(this).attr('target') != undefined && jQuery(this).attr('target').toLowerCase() != '_blank') {
						setTimeout(function() { location.href = baseHref + href; }, 200);
						return false;
					}
				});
			}
		});
	});
}
</script>

The script detects to see if you are opening the file in a new window or not and automatically uses setTimeout() for 200ms if you are not.  If you have multiple tracking objects on a page or have a named tracker, then you’ll want to customize this script.  This script uses the asynchronous ga.js tagging syntax.
Bounce Rate Impact on Tracking File Downloads

When you fire event tracking or a virtual pageview, this will impact your bounce metric in a positive direction.  Events and pageviews count as an interaction.  If you have more than one interaction (pageview or event), then that visit is not counted as a bounce.  Since the visitor took some action on the site, they should not be counted as a bounce anyways, so by coding your file download links, you are actually increasing the accuracy of your metrics.

Related Posts:

    How to Track Downloads & Outbound Links in Google Analytics
    How to Track Downloads & Outbound Links in Universal Analytics
    How to Fully Track the Print Page Action with Google Analytics
    Cross Domain Tracking in Google Analytics
    Website Optimizer Tips for Tracking Complex Conversions

 

Share this Post

    39
    inShare

Joe Christopher

Joe is the Analytics Director and a Partner at Blast Analytics & Marketing. He understands Google Analytics like nobody else and is a master of many programming languages.

Add Joe to your circles on Google+ Joe Christopher has written 31 posts on the Web Analytics Blog.

 

Web Analytics Blog

We're here to help with tips and insight on the following topics:

    Analytics
    Online Marketing
    Search Engine Optimization
    Web Site Optimization

Subscribe to RSS

Optimize your website and marketing campaigns

Get a constant flow of Google Analytics help and online marketing tips, case studies and more from Google Certified Partner Blast Analytics & Marketing.


```

**Comment by cassiopaia** [comment]
anyone who can help me on this tasks? Or just give me a feedback ..if i can use a snippet like this to solve this issue!?

**Comment by akernest** [comment]
being that you are having issues figuring out how to implement tracking for clients downloads within a hidden thank you page, let's just stick with our current approach. feel free to close this issue.

**Comment by cassiopaia** [comment]
i just need to now if i go with the code above …

**Comment by akernest** [comment]
I'm fully aware of the different approaches that we can take in order to track these clicks in Google Analytics, as we already are tracking these clicks as events in Google Analytics. the code I gave you initially, which you installed prior to launch of the new site, is successfully tracking clicks on these links as events in google analytics already. the reason that i wanted to stick with an actual thank you page is that, if any other marketers would like to launch marketing campaigns that require tracking in their own tracking platforms (meaning tracking data in a tracking system other than Google Analytics), having an actual thank you page would give us a place to implement tracking codes from their own tracking systems. if we don't wan't to redirect people to a thank you page, then we need to figure out how to fire tracking codes in a hidden iframe window as dan suggested. otherwise, marketing won't be able to track and optimize their marketing campaigns. i understand user experience is important, but we can't sacrifice our tracking capabilities in order for the user experience to be a 100% ideal experience for the user.

**Comment by akernest** [comment]
i did some more thinking on this last night and came up with an alternative approach where we could all be happy! so there are a few concerns here: (1) we need to track downloads on the main bitshares.org site pages as a goal in analytics (in addition to a click event which is already successfully taking place per my last comment), (2) tracking this event as a goal without having to redirect the user to a thank you page and disrupt user flow on get started page, (3) having a landing page for marketers to use that redirects to a thank you page where marketers can have their custom tracking codes placed for their various tracking systems. with these 3 concerns in mind... we could use the approach i think you were suggesting and track these as a custom onlick event that can be setup as a goal in google analytics. from there, if we can have you create a separate landing page that marketers can use (something like rgcrypto suggested in an email just prior to the new site launch), which would redirect the user to a thank you page where their tracking codes could be placed (we could always refer them to the get started page from the thank you page). what do you think?

**Comment by akernest** [comment]
this was the example that rgcrypto suggested modeling a landing page after: https://btcjam.com/

**Comment by akernest** [comment]
if the suggested compromise works for you, we should follow the example FMV is using on our homepage to accomplish this, as we are using the same custom jquery code to track click events on our site. 

here's an example of the code we have implemented to track a button click as a goal in GA:  

<a  class="x-btn btn-petition x-btn-pill x-btn-large alignright"  title="Support Provably Honest Elections in the U.S." href="https://www.change.org/p/governments-president-of-the-united-states-voting-officials-implement-a-modern-voting-system-where-voters-can-prove-the-election-is-honest-and-accurate" onClick="ga('set', 'nonInteraction', true);ga('send', 'event', { eventCategory: 'button', eventAction: 'click', eventLabel: 'btn-petition'});" target="_blank" data-toggle="none" data-placement="top" data-trigger="hover"   data-options="thumbnail: ''">Support Provably Honest Elections in the U.S.</a>. 

i see that the source code on BTS site looks like this right now for the download button:

<a  class="download"  href="../binaries/BitShares-v0.6.2.exe" onclick="thanks();">
     <div class="large-4 medium-4 small-12 columns outline text-center panel-download ">
     <img style="height: 24px; margin: 0 0 12px 0;" src="../assets/images/icons/windows.svg" />
     <h5>BitShares Client</h5>
     <p><span class="label tiny awesome radius">x32-bit/64-bit</span></p>
     
     
     
     
     </div>
     </a>

based on my example, i think the code should be update to look something like this:

<a  class="download"  href="../binaries/BitShares-v0.6.2.exe" onclick="thanks();ga('set', 'nonInteraction', false);ga('send', 'event', { eventCategory: 'download', eventAction: 'click', eventLabel: 'bitshares_client'});">
     <div class="large-4 medium-4 small-12 columns outline text-center panel-download ">
     <img style="height: 24px; margin: 0 0 12px 0;" src="../assets/images/icons/windows.svg" />
     <h5>BitShares Client</h5>
     <p><span class="label tiny awesome radius">x32-bit/64-bit</span></p>
     
     
     
     
     </div>
     </a>
