### ISSUE TITLE
hide download thank you page

### ISSUE THREAD

**Issue by akernest** [cassiopaia/labs.bitshares.org#17]
needs to be removed from the user experience so that no one actually sees it. to clarify, this url (https://bitshares.org/resources/thankyou) still needs to load to fire tracking codes, but should be done in a hidden iframe window that the user cannot see. this also means that the user won’t be redirect anywhere and can continue on the current page.

**Comment by cassiopaia** [comment]
mh currently i don'T have a solution for this! But with GA you've the opportunity to trak also trigger events! So guess it would be possible with GA scripts instead of creating a hidden iframe.. pls check this before!

**Comment by akernest** [comment]
we need to be able to track this event in more than just Google Analytics. so the proposed work around won't fulfill this requirement. bytemaster said this was possible and that you should know how to do this. if not, please consult bytemaster for further direction on how to accomplish this.

**Comment by cassiopaia** [comment]
ok

**Comment by akernest** [comment]
being that you are having issues figuring out how to implement tracking for clients downloads within a hidden thank you page, let's just stick with our current approach. feel free to close this issue.
