### ISSUE TITLE
change BitShares Decentralized Exchange To BitShares The Decentralized Exchange on Homepage

### ISSUE THREAD

**Issue by akernest** [cassiopaia/labs.bitshares.org#23]
be sure to make BitShares bigger and put it above The Decentralized Exchange, like so, and center them:

BitShares
The Decentralized Exchange

**Comment by cassiopaia** [comment]
https://github.com/cassiopaia/labs.bitshares.org/commit/5ffab496d2ba79f7796f8c3e36871b3cddae75ce
