### ISSUE TITLE
add ”backed by the bitshares (BTS) cryptocurrency" somewhere on homepage

### ISSUE THREAD

**Issue by akernest** [cassiopaia/labs.bitshares.org#27]
ON HOLD - need to get consensus prior to completing request

**Comment by cassiopaia** [comment]
powered by bitshares ? -- I don't think we should add this! BTS is our network.. bitUSD etc. our products!

**Comment by akernest** [comment]
i will talk to bytemaster about this and ask him what he wants to do about this

**Comment by cassiopaia** [comment]
any updates?

**Comment by cassiopaia** [comment]
any updates?
