### ISSUE TITLE
Change wording on https://bitshares.org/resources/thankyou

### ISSUE THREAD

**Issue by growler17** [cassiopaia/labs.bitshares.org#34]
"If you'll need help etc please visit our forum for more detailed infos" 

doesn't read very well... and it does not provide new users an easy way to access our forums! I suggest the following:

<p>If you need additional help, please visit our <a href="www.bitsharestalk.org">forum</a> for more information.</p>

**Comment by cassiopaia** [comment]
https://github.com/cassiopaia/labs.bitshares.org/pull/35
