### ISSUE TITLE
Windows and OS X 'BitShares Client' download buttons do not work on https://bitshares.org/get-started

### ISSUE THREAD

**Issue by growler17** [cassiopaia/labs.bitshares.org#39]
Nothing happens when I click on either of the buttons. Linux link appears to be working fine.

**Comment by cassiopaia** [comment]
which browser u are using?

**Comment by growler17** [comment]
Latest version of Safari 8.0.5 (10600.5.3.1)

**Comment by cassiopaia** [comment]
mh from where you enter download page - Did you get redirected from get started page?

**Comment by cassiopaia** [comment]
Can't reproduce this error, but i'll delete thankyou page soon i'm able to add hidden frames for tracking! Guess if -- thankyou page and redirect will cause this error in some cases ...
