### ISSUE TITLE
Add POLONIEX, remove BTER (temporary I hope)

### ISSUE THREAD

**Issue by liondani** [cassiopaia/labs.bitshares.org#41]
On https://bitshares.org/deposit-withdraw   (exchanges section)

It's  not good new user's end up on BTER home page right now!
Replace maybe with https://www.poloniex.com/
and add https://bittrex.com/ and  https://www.ccedk.com/   also (?)

**Comment by cassiopaia** [comment]
https://github.com/cassiopaia/labs.bitshares.org/pull/42
