### ISSUE TITLE
Make sure download links on /get-started page redirect to /resources/thankyou

### ISSUE THREAD

**Issue by akernest** [cassiopaia/labs.bitshares.org#56]
being that you are having issues figuring out how to implement tracking for clients downloads within a hidden thank you page, let's just stick with our current approach.

with this in mind, we have setup a goal in google analytics to track client downloads for users whom reach this page:

https://bitshares.org/resources/thankyou

users are currently getting redirected to this page upon clicking on any of the download links on the downloads page:

https://bitshares.org/resources/downloads

however, when you added the download links to the /get-started page, you didn't implement the redirects to the thank you page, which means that we are missing out on tracking downloads from this page in google analytics:

https://bitshares.org/get-started

would you please add this functionality to these download links as well?

**Comment by cassiopaia** [comment]
Dan don't want that users have to leave get started page

**Comment by cassiopaia** [comment]
Thats why i've asked here https://github.com/cassiopaia/labs.bitshares.org/issues/16 if could check .. if i can use this snippet or if it could cause problems with GA! I can't say it cause i don't have access to GA!

**Comment by cassiopaia** [comment]
so that means that i'm not thinking, a hidden frame is needed to track downloads! Tracking method like on the code snippet i've added #16 would solve this muc more elegant IMO ..
