### ISSUE TITLE
Update outside resource links to use https where possible (and ideally self-host javascript)

### ISSUE THREAD

**Issue by arhag** [cassiopaia/labs.bitshares.org#7]
https://bitsharestalk.org/index.php?topic=13901.msg181669#msg181669

Currently, all mixed content errors can be solved for all hosts except for faucet.bitshares.org (which appears to be using it for referral tracking purposes?) and api.bitsharesblocks.com (which is necessary for the ticker). 

Also, I that bitshares.org should host the javascript itself rather than trusting outside hosts. Compromised javascript can modify the HTML presented to the viewer (such as the download links and the SHA1 hashes on https://bitshares.org/resources/downloads).

**Comment by cassiopaia** [comment]
yes fixed Google font  and highcharts https issue https://github.com/cassiopaia/labs.bitshares.org/commit/709b2ed0947a78e360068292ec3047a4f85eb91a
