### ISSUE TITLE
Don't include binaries in github checkout it slows things down and will get HUGE

### ISSUE THREAD

**Issue by bytemaster** [cassiopaia/labs.bitshares.org#9]

**Comment by cassiopaia** [comment]
yeah we've done this for tracking purposes! I've advised this also .. but Adam wants to track conversions ... this is why weve also a thank you page! Could you pls talk to Adam!?

**Comment by cassiopaia** [comment]
ok so just link them to specifc download on git!?

**Comment by vikramrajkumar** [comment]
@cassiopaia Can't you just keep them locally but not include them in the git repo?

**Comment by cassiopaia** [comment]
ok yes

**Comment by cassiopaia** [comment]
https://github.com/cassiopaia/labs.bitshares.org/commit/8ef4f14701a591805ea6d65ae3bdf6973bb8f658
